name: HA Git Site Host
slug: git_site_host
version: "1.2.2"
description: Host a static website from a Git repository and auto-update it on an interval.
startup: services
boot: auto
init: false

arch:
  - amd64
  - aarch64
  - armv7
  - armhf
  - i386

ports:
  8099/tcp: 8099

options:
  repo_url: ""
  branch: "main"
  poll_interval: 600
  site_subdir: "dist"
  clean_on_update: true

schema:
  repo_url: str
  branch: str
  poll_interval: int
  site_subdir: str
  clean_on_update: bool